[build]
target = "x86_64-unknown-none"

[target.'cfg(all(target_arch = "x86_64", target_os = "none"))']
rustflags = [
    "-C", "relocation-model=static",
    # 暂时不需要像内核那样指定 linker.ld，除非你要控制加载地址
    # 但必须指定这个，否则也会报错
]
